import { Blog } from "../types";

export const blogs: Blog[] = [
  {
    id: 1,
    title: "Mastering React in 2025",
    content:
      "Learn about the latest trends and techniques to become a React expert. This comprehensive guide covers hooks, state management, performance optimization, and much more to elevate your React skills.",
    author: "John Doe",
    authorAvatar: "/api/placeholder/30/30",
    createdAt: "2025-04-01",
    readTime: "8 min read",
    tags: ["React", "Frontend", "JavaScript"],
    featured: true,
    likes: 243,
    bookmarks: 89,
  },
  {
    id: 2,
    title: "Understanding RBAC for Web Apps",
    content:
      "Role-Based Access Control is crucial for securing modern web applications. Discover how to implement robust authentication systems that protect user data while providing a seamless experience.",
    author: "Jane Smith",
    authorAvatar: "/api/placeholder/30/30",
    createdAt: "2025-04-05",
    readTime: "12 min read",
    tags: ["Security", "Backend", "Authentication"],
    featured: false,
    likes: 187,
    bookmarks: 124,
  },
  {
    id: 3,
    title: "Scaling Node.js Applications",
    content:
      "Strategies for scaling your Node.js apps to handle millions of users. We'll explore clustering, load balancing, caching strategies, and database optimization techniques for high-traffic applications.",
    author: "Michael Johnson",
    authorAvatar: "/api/placeholder/30/30",
    createdAt: "2025-04-10",
    readTime: "10 min read",
    tags: ["Node.js", "Backend", "Performance"],
    featured: true,
    likes: 321,
    bookmarks: 176,
  },
  {
    id: 4,
    title: "Top 10 VSCode Extensions in 2025",
    content:
      "Boost your productivity with these must-have extensions for modern web development. From AI-powered code completion to advanced debugging tools, these extensions will transform your workflow.",
    author: "Emily Davis",
    authorAvatar: "/api/placeholder/30/30",
    createdAt: "2025-04-11",
    readTime: "6 min read",
    tags: ["Tools", "Productivity", "VSCode"],
    featured: false,
    likes: 154,
    bookmarks: 98,
  },
  {
    id: 5,
    title: "What's New in ECMAScript 2025",
    content:
      "A deep dive into the new features of JavaScript that will reshape how we write code. Explore the latest syntax improvements, built-in functions, and performance enhancements.",
    author: "Chris Wilson",
    authorAvatar: "/api/placeholder/30/30",
    createdAt: "2025-04-15",
    readTime: "11 min read",
    tags: ["JavaScript", "Frontend", "ECMAScript"],
    featured: true,
    likes: 276,
    bookmarks: 143,
  },
  {
    id: 6,
    title: "Introduction to MongoDB Atlas",
    content:
      "Deploy and manage your databases easily with MongoDB Atlas. Learn how cloud database services can simplify your infrastructure while providing enterprise-grade reliability and security.",
    author: "Sara Lee",
    authorAvatar: "/api/placeholder/30/30",
    createdAt: "2025-04-16",
    readTime: "9 min read",
    tags: ["Database", "MongoDB", "Backend"],
    featured: false,
    likes: 198,
    bookmarks: 87,
  },
  {
    id: 7,
    title: "Why TypeScript is a Game Changer",
    content:
      "Understand why companies are moving towards TypeScript heavily. Discover how static typing can prevent runtime errors, improve code quality, and enhance team collaboration on large projects.",
    author: "David Brown",
    authorAvatar: "/api/placeholder/30/30",
    createdAt: "2025-04-18",
    readTime: "7 min read",
    tags: ["TypeScript", "Frontend", "JavaScript"],
    featured: false,
    likes: 231,
    bookmarks: 112,
  },
  {
    id: 8,
    title: "A Guide to Serverless Architectures",
    content:
      "Serverless is the future, and here's how you can adapt. Learn about FaaS providers, event-driven architectures, and how to refactor existing applications to leverage serverless benefits.",
    author: "Anna White",
    authorAvatar: "/api/placeholder/30/30",
    createdAt: "2025-04-20",
    readTime: "13 min read",
    tags: ["Serverless", "Cloud", "Architecture"],
    featured: true,
    likes: 287,
    bookmarks: 156,
  },
  {
    id: 9,
    title: "Monorepos: Should You Use Them?",
    content:
      "Pros and cons of Monorepo strategies for large applications. We'll examine real-world case studies, tooling options, and best practices for organizing code in growing organizations.",
    author: "Robert King",
    authorAvatar: "/api/placeholder/30/30",
    createdAt: "2025-04-22",
    readTime: "8 min read",
    tags: ["Monorepo", "Tools", "Architecture"],
    featured: false,
    likes: 165,
    bookmarks: 74,
  },
  {
    id: 10,
    title: "Understanding OAuth 2.0 and OpenID",
    content:
      "Secure your apps properly with OAuth and OpenID best practices. This comprehensive guide covers implementation strategies, common vulnerabilities, and the latest security recommendations.",
    author: "Laura Scott",
    authorAvatar: "/api/placeholder/30/30",
    createdAt: "2025-04-24",
    readTime: "10 min read",
    tags: ["Security", "Authentication", "OAuth"],
    featured: false,
    likes: 209,
    bookmarks: 118,
  },
  {
    id: 11,
    title: "How AI is Changing Software Development",
    content:
      "AI tools like GitHub Copilot are redefining developer productivity. Explore how machine learning is transforming code completion, bug detection, and even architectural decision-making.",
    author: "Nina Allen",
    authorAvatar: "/api/placeholder/30/30",
    createdAt: "2025-04-26",
    readTime: "9 min read",
    tags: ["AI", "Productivity", "Tools"],
    featured: true,
    likes: 342,
    bookmarks: 187,
  },
  {
    id: 12,
    title: "Master TailwindCSS in 2025",
    content:
      "Learn how to build fast, responsive UIs using TailwindCSS. This guide covers advanced utilities, component patterns, dark mode strategies, and custom extension techniques.",
    author: "Jack Martin",
    authorAvatar: "/api/placeholder/30/30",
    createdAt: "2025-04-27",
    readTime: "11 min read",
    tags: ["TailwindCSS", "CSS", "Frontend"],
    featured: false,
    likes: 253,
    bookmarks: 131,
  },
];
